wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.5
      5: 0.10.32
      8:
      - 5
batch_size:
  desc: null
  value: 128
communicate_round:
  desc: null
  value: 20
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.1
