name: fedlab
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py39h06a4308_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - ipykernel=5.3.4=py39hb070fc8_0
  - ipython=7.22.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39h06a4308_1
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - parso=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.1.1=py39h06a4308_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - python=3.9.5=hdb3f193_3
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py39h2531618_1
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py39h06a4308_0
  - six=1.15.0=py39h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2020f=h52ac0ba_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - chardet==4.0.0
    - click==8.0.1
    - configparser==5.0.2
    - docker-pycreds==0.4.0
    - gitdb==4.0.7
    - gitpython==3.1.18
    - idna==2.10
    - numpy==1.20.3
    - pathtools==0.1.2
    - pillow==8.2.0
    - promise==2.3
    - protobuf==3.17.3
    - psutil==5.8.0
    - pycodestyle==2.7.0
    - pyyaml==5.4.1
    - requests==2.25.1
    - sentry-sdk==1.1.0
    - shortuuid==1.0.1
    - smmap==4.0.0
    - subprocess32==3.5.4
    - toml==0.10.2
    - torch==1.7.1+cu101
    - torchaudio==0.7.2
    - torchvision==0.8.2+cu101
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5
    - wandb==0.10.32
    - yapf==0.31.0
prefix: /home/zengdun/anaconda3/envs/fedlab
